article_module/urls.py
from django.urls import path
from article_module import views

urlpatterns = [
    path('', views.ArticleList.as_view(), name='article_list'),
    path('cat/<str:category>', views.ArticleList.as_view(), name='article_category_list_filter'),
    path('<pk>', views.ArticleDetailView.as_view(), name='article_detail_page')
]

article_module/models.py
from django.db import models
from user_module.models import User


class ArticleCategory(models.Model):
    parent = models.ForeignKey('ArticleCategory', null=True, blank=True, on_delete=models.CASCADE,
                               verbose_name='دسته بندی والد')
    title = models.CharField(max_length=200, verbose_name='عنوان دسته بندی')
    url_title = models.CharField(max_length=200, unique=True, verbose_name='عنوان در url')
    is_active = models.BooleanField(default=True, verbose_name='فعال / غیرفعال')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'دسته بندی مقاله'
        verbose_name_plural = 'دسته بندی های مقاله'


# Create your models here.
class ArticleModel(models.Model):
    title = models.CharField(max_length=300, verbose_name='عنوان مقاله')
    slug = models.SlugField(max_length=400, db_index=True, allow_unicode=True, verbose_name='عنوان در url')
    image = models.ImageField(upload_to='images/articles', verbose_name='تصویر مقاله')
    short_description = models.TextField(verbose_name='توضیحات کوتاه')
    text = models.TextField(verbose_name='متن مقاله')
    is_active = models.BooleanField(default=True, verbose_name='فعال / غیرفعال')
    selected_categories = models.ManyToManyField(ArticleCategory, verbose_name='دسته بندی ها')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='نویسنده', null=True, editable=False)
    create_date = models.DateTimeField(auto_now_add=True, editable=False, verbose_name='تاریخ ثبت')

    def __str__(self):
        return self.title


class Meta:
    verbose_name = 'مقاله'
    verbose_name_plural = 'مقالات'

article_module/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from article_module import models


# Create your views here.
class ArticleList(ListView):
    model = models.ArticleModel
    paginate_by = 5
    template_name = 'article_module/article_list.html'

    def get_queryset(self):
        query = super(ArticleList, self).get_queryset()
        query = query.filter(is_active=True)
        category_name = self.kwargs.get('category')
        if category_name is not None:
            query = query.filter(selected_categories__url_title__iexact=category_name)
        return query


def article_category_component(request):
    context = {
        'categories': models.ArticleCategory.objects.filter(is_active=True, parent_id=None)
    }
    return render(request, 'components/article_category_component.html', context)


class ArticleDetailView(DetailView):
    model = models.ArticleModel
    template_name = 'article_module/article_detail.html'
    context_object_name = 'article'

article_module/templates/article_module/article_list.html
{% extends 'shared/layout.html' %}
{% load thumbnail %}
{% load poll_extras %}
{% load render_partial %}
{% block title %}
    مقالات
{% endblock %}
{% block content %}
    <section>
        <div class="container">
            <div class="row">

                <div class="col-sm-9">
                    <div class="blog-post-area">
                        <h2 class="title text-center">آخریـن اخبـار</h2>
                        {% for object in object_list %}
                            <div class="single-blog-post">
                                <h3>{{ object.title }}</h3>
                                <div class="post-meta">
                                    <ul>
                                        {% if object.author %}
                                            <li><i class="fa fa-user"></i>{{ object.author }}</li>{% endif %}
                                        <li><i class="fa fa-clock-o"></i> {{ object.create_date|jalali_time }}</li>
                                        <li><i class="fa fa-calendar"></i>{{ object.create_date|jalali_date }}</li>
                                    </ul>
                                    <span>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star-half-o"></i>
								</span>
                                </div>
                                <a href="">
                                    {% thumbnail object.image '862x398' as image %}
                                        <img src="{{ image.url }}" alt="">
                                    {% endthumbnail %}

                                </a>
                                <p>{{ object.short_description }}</p>
                                <a class="btn btn-primary" href="">ادامـه مطلب</a>
                            </div>

                        {% endfor %}

                        <div class="pagination-area">
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    <li class="">
                                        <a href="?page={{ page_obj.previous_page_number }}">قبلی</a>
                                    </li>
                                {% endif %}
                                {% for page in paginator.page_range %}
                                    <li><a href="?page={{ page }}"
                                           class="{% if page_obj.number == page %}active{% endif %}">{{ page }}</a></li>

                                {% endfor %}
                                {% if page_obj.has_next %}
                                    <li>
                                        <a href="?page={{ page_obj.next_page_number }}">بعدی</a>
                                    </li>


                                {% endif %}

                            </ul>
                        </div>
                    </div>
                </div>

                {% render_partial 'article_module.views.article_category_component' %}
                <h2>برنـد ها</h2>
                <div class="brands-name">
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href=""> <span class="pull-left">(50)</span>برنـد 1</a></li>
                        <li><a href=""> <span class="pull-left">(56)</span>برنـد 2</a></li>
                        <li><a href=""> <span class="pull-left">(27)</span>برنـد 3</a></li>
                        <li><a href=""> <span class="pull-left">(32)</span>برنـد 4</a></li>
                        <li><a href=""> <span class="pull-left">(5)</span>برنـد 5</a></li>
                    </ul>
                </div>
            </div><!--/brands_products-->

            <div class="price-range"><!--price-range-->
                <h2>فیلتـر قیمـت</h2>
                <div class="well">
                    <div class="slider slider-horizontal" style="width: 176px;">
                        <div class="slider-track">
                            <div class="slider-selection" style="left: 0.025%; width: 0.0199999%;"></div>
                            <div class="slider-handle round left-round" style="left: 0.025%;"></div>
                            <div class="slider-handle round" style="left: 0.045%;"></div>
                        </div>
                        <div class="tooltip top" style="top: -30px; left: -30.4384px;">
                            <div class="tooltip-arrow"></div>
                            <div class="tooltip-inner">250 : 450</div>
                        </div>
                        <input type="text" class="span2" value="" data-slider-min="0"
                               data-slider-max="1000000" data-slider-step="5" data-slider-value="[250,450]"
                               id="sl2" style=""></div>
                    <br>
                    <b>1.000.000 ريال</b> <b class="pull-left">0 ريال</b>
                </div>
            </div><!--/price-range-->

            <div class="shipping text-center"><!--shipping-->
                <img src="/static/images/home/shipping.jpg" alt="">
            </div><!--/shipping-->

        </div>
        </div>

        </div>
        </div>
    </section>
{% endblock %}

article_module/templates/components/article_category_component.html
<div class="col-sm-3">
    <div class="left-sidebar">
        <h2>دسته بندی محصولات</h2>
        <div class="panel-group category-products" id="accordian"><!--category-productsr-->

 {% for item in categories %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    {% if item.articlecategory_set.all %}
                        <a data-toggle="collapse" data-parent="#accordian" href="#{{ item.url_title }}">
                            <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                            {{ item.title }}
                        </a>

                    {% else %}
                        <a href="{% url 'article_category_list_filter' category=item.url_title %}">
                            {{ item.title }}
                        </a>
                    {% endif %}
                </h4>
            </div>
            {% if item.articlecategory_set.all %}
                <div id="{{ item.url_title }}" class="panel-collapse collapse">
                    <div class="panel-body">
                        <ul>
                            {% for sub_category in item.articlecategory_set.all %}
                                <li>
                                    <a href="{% url 'article_category_list_filter' category=sub_category.url_title %}"> {{ sub_category.title }} </a>
                                </li>
                            {% endfor %}

                        </ul>
                    </div>
                </div>
            {% endif %}
        </div>
    {% endfor %}
        </div><!--/category-productsr-->

        <div class="brands_products"><!--brands_products-->